### ISSUE TITLE
Dates in the EndNote Export format

### ISSUE THREAD

**Issue by mouradvt04** [rayyansys/ref_parsers#14] opened 2020-05-28 08:35 UTC
We need to do a better job at extracting dates from the EndNote Export format. Currently, Rayyan only read the date in the "%D" field and ignore the information in the "%7" and "%8" fields. See here for the meaning of these different fields https://en.wikipedia.org/wiki/EndNote#Import_format.

**Comment by hammady** [comment] 2022-06-24 16:40
Duplicate of https://github.com/rayyansys/rayyan-formats-plugins/issues/10.

**Closed by hammady** 2022-06-24 16:40 UTC
